# Generated by Django 4.1.2 on 2022-10-19 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_tag_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken',
            new_name='Token',
        ),
    ]
