# Generated by Django 4.1.2 on 2022-10-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_token_user_alter_usersettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
