# Generated by Django 4.1.2 on 2022-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usersettings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
