# Generated by Django 4.1.2 on 2022-12-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='breakTime',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='focusTime',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='startSound',
            field=models.CharField(choices=[('DI', 'ding'), ('NA', 'nanana')], default='DI', max_length=2),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='stopSound',
            field=models.CharField(choices=[('MI', 'minion'), ('WH', 'whoose')], default='WH', max_length=2),
        ),
    ]
