# Generated by Django 4.1.2 on 2022-12-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usersettings_breaktime_usersettings_focustime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='breakColor',
            field=models.CharField(default='#ADFF2F', max_length=7),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='focusColor',
            field=models.CharField(default='#f1c232', max_length=7),
        ),
    ]
