# Generated by Django 4.1.2 on 2022-12-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_usersettings_startsound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='focusTime',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='stopSound',
            field=models.CharField(choices=[('#minion', 'minion'), ('#whoosh', 'whoosh')], default='#whoosh', max_length=16),
        ),
    ]
