# Generated by Django 4.1.2 on 2022-12-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_usersettings_focustime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='focusTime',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
