# Generated by Django 4.1.4 on 2022-12-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_usersettings_longbreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='token',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
