# Generated by Django 4.1.2 on 2022-12-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='token',
            field=models.CharField(default='jrKdTnTsL2Ayq0mOk1e4hg', max_length=27, null=True),
        ),
    ]
