# Generated by Django 4.1.2 on 2023-01-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_usersettings_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='token',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
    ]
