# Generated by Django 4.1.2 on 2023-01-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_usersettings_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='breakTime',
            new_name='shortBreak',
        ),
    ]
