# Generated by Django 4.1.2 on 2023-01-17 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_breaktime_usersettings_shortbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='startSound',
            field=models.CharField(choices=[('#ding', 'ding'), ('#folks', 'nanana')], default='#ding', max_length=16),
        ),
    ]
