# Generated by Django 4.1.2 on 2023-01-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='white_theme',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('white', 'white'), ('forest', 'forest'), ('aquamarine', 'aquamarine'), ('garnet', 'garnet'), ('coral', 'coral')], default='default', max_length=16),
        ),
    ]
