# Generated by Django 4.2.3 on 2023-07-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_usersettings_white_theme_usersettings_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='image',
            field=models.CharField(default='default.png', max_length=256),
        ),
    ]
