# Generated by Django 4.2.4 on 2023-08-19 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_statistics_alter_usersettings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='ranks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
        ),
    ]
